# 网站的基本URL
baseURL: 'https://iflab.github.io/bistuios.github.io/'

# 语言代码
languageCode: 'zh-CN'

# 使用的主题
theme: "hello-friend-4s3ti"

# 网站标题
title: 'Bistu iOS Club'

# 版权声明
copyright: "All Rights Reserved"

# 是否启用多语言支持
IsMultiLingual: true

# 主题参数
params:
  # 版本号
  version: "dev"
  
  # 作者信息
  author: 
    name: "BistuiOS Club"
  
  # 默认主题（例如：dark, light）
  defaultTheme: "dark"
  
  # 是否启用主题切换
  EnableThemeToggle: true 
  
  # Git仓库URL
  gitUrl: "https://iflab.github.io/bistuios.github.io/"
  
  # 是否启用分享按钮
  EnableSharingButtons: true
  
  # 是否启用全局语言菜单
  EnableGlobalLanguageMenu: true
  
  # 背景图片路径
  backgroundImage: "static/coolapso.png"
  
  # 是否启用背景效果
  backgroundEffects: true
  
  # 是否显示文章列表
  showPosts: true
  
  # 是否显示标签
  tags: true
  
  # 阅读更多文本
  ReadMoreText: true
  
  # FontAwesome 图标库设置
  fontAwesome: 
    all: true
    # 可以单独启用或禁用不同的图标类型
    # brands: true
    # solid: true
    # regular: true
    # kitURL: "https://kit.fontawesome.com/yourkitid.js"
  
  # 是否显示阅读时间
  ShowReadingTime: true
  
  # 是否显示最后修改时间
  LastModDisplay: true
  
  # 标签设置
  tags: true
  
  # Logo 设置
  logo:
    logoText: "coolapso.sh"
    logoCursorColor: "#ffffff"
  
  # 社交媒体链接
  social:
    - name: "github"
      url: "https://github.com/coolapso"
    - name: "website"
      url: "https://coolapso.sh"
      icon: fa-solid fa-terminal
    - name: "youtube"
      url: "https://youtube.com/@ccoolapso"
    - name: "x-twitter"
      url: "https://x.com/ccoolapso"
    - name: "instagram"
      url: "https://www.instagram.com/c4colaco/"
    - name: "twitch"
      url: "https://twitch.tv/cool4pso"
    - name: "Buy me a coffee"
      url: "https://www.buymeacoffee.com/coolapso"
      icon: fa-solid fa-coffee
  
  # 页脚设置
  footer:
    # 是否显示版本号
    showVersion: true
    
    # 是否显示社交媒体图标
    socialIcons: true
    
    # 是否显示作者信息
    author: true
    
    # 是否显示RSS订阅链接
    rss: true
    
    # 是否显示商标
    trademark: true
    
    # 是否显示版权声明
    copyright: true
    
    # 页脚顶部文本
    # topText:  ["Footer Top text"]
    
    # 页脚底部文本
    bottomText: [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
      "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>",
    ]

# 分类法设置
taxonomies:
  tag: "tags"
  category: "blog"

# 菜单设置
menu:
  main:
    - identifier: "about"
      name: "荣誉"
      url: "#"
      weight: 2

    - identifier: "posts"
      name: "关于我们"
      url: "/posts"
      weight: 1

    - identifier: "tools"
      name: "成员"

    - identifier: "projects"
      name: "项目"
      url: "/projects"