baseURL: 'https://iflab.github.io/bistuios.github.io/'
languageCode: 'zh-CN'
theme: "hello-friend-4s3ti"
title: 'Bistu iOS Club'
copyright: "All Rights Reserved"
IsMultiLingual: true







params:
  version: "dev"
  author: 
    name: "BistuiOS Club"
  defaultTheme: "dark"
  EnableThemeToggle: true 
# gitUrl: "https://github.com/4s3ti"
  EnableSharingButtons: true
  EnableGlobalLanguageMenu: true
  backgroundImage: "static/coolapso.png"
  backgroundEffects: true
  showPosts: true
  tags: true
# hideReadMore: true
  ReadMoreText: true
# ReadMore: "foo"
# socialIcons: true
# homeTitle: "Title"
# homeSubtitle: "Subtitle"
  fontAwesome: 
    all: true
    # brands: true
    # solid: true
    # regular: true
    # kitURL: "https://kit.fontawesome.com/yourkitid.js"
  ShowReadingTime: true
  LastModDisplay: true
  tags: true
  logo:
    logoText: "coolapso.sh"
    logoCursorColor: "#ffffff"
  social:
    - name: "github"
      url: "https://github.com/coolapso"
    - name: "website"
      url: "https://coolapso.sh"
      icon: fa-solid fa-terminal
    - name: "youtube"
      url: "https://youtube.com/@ccoolapso"
    - name: "x-twitter"
      url: "https://x.com/ccoolapso"
    - name: "instagram"
      url: "https://www.instagram.com/c4colaco/"
    - name: "twitch"
      url: "https://twitch.tv/cool4pso"
    - name: "Buy me a coffee"
      url: "https://www.buymeacoffee.com/coolapso"
      icon: fa-solid fa-coffee
  footer:
    showVersion: true
    socialIcons: true
    author: true
    rss: true
    trademark: true
    copyright: true
#   topText:  ["Footer Top text"]
    bottomText: [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>", 
      "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>",
    ]
    


taxonomies:
  tag: "tags"
  category: "blog"

menu:
  main:
    - identifier: "about"
      name: "Sobre"
      url: "#"
      weight: 2

    - identifier: "posts"
      name: "Posts"
      url: "/posts"
      weight: 1

    - identifier: "tools"
      name: "Ferramentas"

    - identifier: "projects"
      name: "Projetos"
      url: "/projects"

    - identifier: "Projeto 1"
      name: "Projeto 1"
      url: "#"
      parent: "projects"
    - identifier: "ferramenta 1"
      name: "Ferramenta 1"
      url: "#"
      parent: "tools"
    - identifier: "Ferramenta 2"
      name: "Ferramenta 2"
      parent: "tools"
      url: "#"
    - identifier: "Ferramenta 3"
      name: "Ferramenta 3"
      parent: "tools"
      url: "#"
