baseURL = ""  # 站点的基础 URL
title = "My Blog"  # 站点标题
languageCode = "zh-CN"  # 语言代码
theme = "hello-4s3ti"  # 使用的主题
paginate = 10  # 每页显示的文章数量

[params]
  dateform = "2006年1月2日"  # 日期格式
  dateformShort = "1月2日"  # 简短日期格式
  dateformNum = "2006-01-02"  # 数字日期格式
  dateformNumTime = "2006-01-02 15:04"  # 数字日期时间格式

  # 首页副标题
  homeSubtitle = "Welcome to the bistuiOS Club"

  # 设置为 true 以隐藏其他文章的链接
  disableReadOtherPosts = false

  # 启用分享按钮
  enableSharingButtons = true

  # 主要用于文档头部的元数据
  description = "我的新主页或博客"
  keywords = "主页, 博客"
  images = [""]  # 用于社交媒体分享的图像 URL 列表

  # 背景图片
  backgroundImage = "/images/background.jpg"  # 指定背景图片的路径

[taxonomies]  # 分类法
  category = "blog"  # 分类分类法
  tag = "tags"  # 标签分类法
  series = "series"  # 系列分类法

  # 创建通用菜单
  [[menu.main]]
    identifier = "blog"
    name = "关于我们"
    url = "/posts"